org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=kubejs
archives_base_name=kubejs-neoforge
mod_name=KubeJS
maven_group=dev.latvian.mods
mod_author=latvian.dev
curseforge_id=238086
modrinth_id=umyGl7zF

minecraft_version=26.1-snapshot-6
supported_versions=26.1-snapshot-6, 26.1-snapshot-6
mod_version=2601.7.2

neoforge_version=26.1.0.0-alpha.8+snapshot-4
neoforge_version_range=[26.1.0.0-alpha,)
rhino_version=2101.2.7-build.81
tiny_server_version=1.0.0-build.33
gif_lib_version=1.7
bat_version=2101.1.0-build.1

architectury_version=13.0.8
rei_version=16.0.799
jei_version=19.25.0.322
emi_version=1.1.22