import org.gradle.api.initialization.resolve.RepositoriesMode
import org.gradle.api.initialization.resolve.RulesMode

pluginManagement {
	repositories {
		mavenLocal()
		gradlePluginPortal()
		mavenCentral()
		maven { url "https://maven.neoforged.net/releases" }
		maven { url "https://maven.creeperhost.net/" }
	}
	plugins {
		// https://projects.neoforged.net/neoforged/ModDevGradle
		id 'net.neoforged.moddev' version '2.0.134'
		id 'net.neoforged.moddev.repositories' version '2.0.134'
	}
}

plugins {
	id 'net.neoforged.moddev.repositories'
	id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
	repositoriesMode = RepositoriesMode.FAIL_ON_PROJECT_REPOS
	rulesMode = RulesMode.FAIL_ON_PROJECT_RULES
	repositories {
		maven {
			// location of the maven that hosts JEI files
			name = "Progwml6 maven"
			url = "https://dvs1.progwml6.com/files/maven/"
		}
		maven {
			// location of a maven mirror for JEI files, as a fallback
			name = "ModMaven"
			url = "https://modmaven.dev"
		}
		maven {
			url = 'https://maven.shedaniel.me/'
			content {
				includeGroup 'me.shedaniel'
				includeGroup 'me.shedaniel.cloth'
				includeGroup 'dev.architectury'
			}
		}
		maven {
			name = 'cursemaven'
			url = 'https://www.cursemaven.com'
			content {
				includeGroup 'curse.maven'
			}
		}

		maven {
			url = 'https://maven.blamejared.com/'
			content {
				includeGroup 'mezz.jei'
			}
		}
		maven {
			name = 'ParchmentMC'
			url = 'https://maven.parchmentmc.org'
			content {
				includeGroup "org.parchmentmc.data"
			}
		}

		maven {
			url "https://maven.latvian.dev/releases"
			content {
				includeGroup "dev.latvian.mods"
				includeGroup "dev.latvian.apps"
			}
		}
		maven {
			url "https://maven.latvian.dev/mirror"
			content {
				includeGroup "dev.architectury"
				includeGroup "me.shedaniel"
				includeGroup "me.shedaniel.cloth"
				includeGroup "mezz.jei"
				includeGroup "net.darkhax.bookshelf"
				includeGroup "net.darkhax.gamestages"
				includeGroup "dev.emi"
				includeGroup "com.github.rtyley"
			}
		}
		mavenCentral()
	}
}
rootProject.name = 'KubeJS-26.1'
