package dev.latvian.mods.kubejs.recipe;

import dev.latvian.mods.kubejs.recipe.component.RecipeComponent;
import dev.latvian.mods.kubejs.recipe.schema.RecipeOptional;
import dev.latvian.mods.kubejs.recipe.schema.RecipeSchema;
import dev.latvian.mods.kubejs.util.UtilsJS;

import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * Represents a typed data key in a recipe schema. This refers to both the literal "key" used in the recipe JSON
 * and to a "holder" that can be used to lookup and set data in the recipe itself. It is also used by recipe constructors
 * in order to determine the order and types of arguments, as well as whether those arguments are optional or not.
 * <p>
 * A key is always associated with a {@link RecipeComponent} which represents the type of data that it holds.
 * <p>
 * Each recipe key has set of {@link #names} that it may be called by in JSON, as well as a {@link #preferred} name
 * used in autogenerated methods and a primary {@link #name} used for serialization.
 * <p>
 * A key may also be {@link #optional}, which means that its value may not always be present in JSON and will also not
 * be serialized unless it is declared as {@link #alwaysWrite}.
 * <p>
 * By default, each key will have a "builder" method generated for scripts using the {@link #preferred} name.
 * You can disable this by setting {@link #excluded} to true.
 * <p>
 * Finally, some types of components such as items or fluids may perform validation to ensure that they
 * aren't holding empty data. If empty data should explicitly be allowed, you can set {@link #allowEmpty} to true.
 *
 * @param <T> The type of element held by this key's component
 * @see RecipeSchema
 * @see RecipeComponent
 */
public final class RecipeKey<T> {
	public final RecipeComponent<T> component;
	public final String name;
	public final Set<String> names;
	public String preferred;
	public RecipeOptional<T> optional;
	public boolean excluded;
	public boolean allowEmpty;
	public boolean alwaysWrite;

	public RecipeKey(RecipeComponent<T> component, String name) {
		this.component = component;
		this.name = name;
		this.names = new LinkedHashSet<>(1);
		this.names.add(name);
		this.preferred = name;
		this.optional = null;
		this.excluded = false;
		this.allowEmpty = false;
		this.alwaysWrite = false;
	}

	@Override
	public int hashCode() {
		return name.hashCode();
	}

	@Override
	public String toString() {
		var sb = new StringBuilder(name);

		if (optional != null) {
			sb.append('?');
		}

		sb.append(':');
		sb.append(component);
		return sb.toString();
	}

	/**
	 * Sets this key to not be required in json and constructor
	 *
	 * @param value The default value of this key if not otherwise defined
	 */
	public RecipeKey<T> optional(T value) {
		return optional(new RecipeOptional.Constant<>(value));
	}

	/**
	 * Sets this key to not be required in json and constructor
	 *
	 * @param value A function used to compute the default value of this key if not otherwise defined
	 */
	public RecipeKey<T> optional(RecipeOptional<T> value) {
		optional = value;
		return this;
	}

	/**
	 * Sets this key to not be required in json and constructor, with a default value of <code>null</code>
	 *
	 * @implNote Use this in place of regular optional(x) only if the value is dynamic/too complicated to compute from type
	 */
	public RecipeKey<T> defaultOptional() {
		optional = UtilsJS.cast(RecipeOptional.DEFAULT);
		return this;
	}

	public boolean optional() {
		return optional != null;
	}

	/**
	 * Adds an alternate name for this key in JSON
	 *
	 * @param name Another name this key may be called by
	 */
	public RecipeKey<T> alt(String name) {
		names.add(name);
		return this;
	}

	/**
	 * Adds multiple alternate names for this key in JSON
	 *
	 * @param names A list of names this key may be called by
	 */
	public RecipeKey<T> alt(String... names) {
		this.names.addAll(List.of(names));
		return this;
	}

	/**
	 * Sets the <b>preferred</b> name for this key, used when generating builder methods
	 * or documentation (using third-party mods such as ProbeJS)
	 */
	public RecipeKey<T> preferred(String name) {
		names.add(name);
		preferred = name;
		return this;
	}

	/**
	 * Excludes this key from auto-generated constructors. <i>Requires</i> optional() value to also be set.
	 */
	public RecipeKey<T> exclude() {
		excluded = true;
		return this;
	}

	public boolean includeInAutoConstructors() {
		return optional == null || !excluded;
	}

	/**
	 * Allow empty values (such as minecraft:air) in results/ingredients
	 */
	public RecipeKey<T> allowEmpty() {
		allowEmpty = true;
		return this;
	}

	/**
	 * Set this in order to always write optional keys, even if their value hasn't changed
	 */
	public RecipeKey<T> alwaysWrite() {
		alwaysWrite = true;
		return this;
	}
}
