name: Feature Request
description: Suggest a feature/enhancement for KubeJS
labels: [ enhancement ]
body:

  - type: textarea
    id: description
    attributes:
      label: Describe the feature
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: Why should this be considered? Are there any alternatives?