name: Release

on:
  workflow_dispatch:
    inputs:
      target_version:
        type: string
        required: false
        description: "mod version | empty = next option"
      update_type:
        type: choice
        required: false
        description: "update type"
        default: "minor"
        options:
          - "major"
          - "minor"
          - "patch"
          - "none"
      release_type:
        type: choice
        required: true
        description: "type of release"
        default: "release"
        options:
          - "alpha"
          - "beta"
          - "release"
      debug:
        type: boolean
        required: false
        default: false
        description: "enable debug mode (GitHub only)"

jobs:
  redirect:
    uses: KubeJS-Mods/.github/.github/workflows/release-nf.yml@main
    secrets: inherit
    with:
      java-distribution: "microsoft"
      java-version: "25"
      mod_name: "KubeJS"
      curseforge_id: "238086"
      modrinth_id: "umyGl7zF"
      dependencies: |
        rhino(required){curseforge:416294}{modrinth:sk9knFPE}
        jei(optional){curseforge:238222}{modrinth:u6dRKJwZ}
        rei(optional){curseforge:310111}{modrinth:nfn13YXA}
        emi(optional){curseforge:580555}{modrinth:fRiHVvU7}
      target_version: ${{ github.event.inputs.target_version }}
      update_type: ${{ github.event.inputs.update_type }}
      release_type: ${{ github.event.inputs.release_type }}
      loaders: "neoforge"
      debug: ${{ github.event.inputs.debug }}
      maven_url: "https://maven.latvian.dev/releases"
      maven_username: "lat"
