name: Release (2101)

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release Type"
        required: true
        type: choice
        default: "release"
        options:
          - "release"
          - "beta"
          - "alpha"
          - "none"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Increment build number
        id: build_number
        env:
          GH_TOKEN: ${{ secrets.BUILD_NUMBER_TOKEN }}
        run: |
          current=$(gh api repos/$GITHUB_REPOSITORY/actions/variables/BUILD_NUMBER_2101 --jq '.value')
          next=$((current + 1))
          gh variable set BUILD_NUMBER_2101 --body "$next" --repo "$GITHUB_REPOSITORY"
          echo "number=$next" >> "$GITHUB_OUTPUT"

      - name: Build with Gradle
        run: ./gradlew build -x test --stacktrace
        env:
          BUILD_NUMBER: ${{ steps.build_number.outputs.number }}

      - name: Publish to latvian.dev Maven
        run: ./gradlew publish --stacktrace
        env:
          BUILD_NUMBER: ${{ steps.build_number.outputs.number }}
          MAVEN_URL: "https://maven.latvian.dev/releases"
          MAVEN_USERNAME: "lat"
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}

      - name: Publish to saps.dev Maven
        run: ./gradlew publish --stacktrace
        env:
          BUILD_NUMBER: ${{ steps.build_number.outputs.number }}
          MAVEN_URL: "https://maven.saps.dev/releases"
          MAVEN_USERNAME: "latvian"
          MAVEN_TOKEN: ${{ secrets.SAPS_TOKEN }}

      - name: Release to CurseForge
        if: ${{ inputs.release_type != 'none' }}
        run: ./gradlew publishCurseforge --stacktrace
        env:
          BUILD_NUMBER: ${{ steps.build_number.outputs.number }}
          CURSEFORGE_KEY: ${{ secrets.CURSEFORGE_KEY }}
          RELEASE_TYPE: ${{ inputs.release_type }}

      - name: Release to Modrinth
        if: ${{ inputs.release_type != 'none' }}
        run: ./gradlew publishModrinth --stacktrace
        env:
          BUILD_NUMBER: ${{ steps.build_number.outputs.number }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          RELEASE_TYPE: ${{ inputs.release_type }}
